[package]
name = "syg"
description = "Like syn, but only signatures and with resolved types"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = {version = "2.0.68", features = ["full", "visit", "extra-traits"]}
extend = "1.2.0"
quote = "1.0.36"
